{{- if .Values.aws.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.poller.secretRef }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: {{ .Values.poller.secretRef }}
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: {{ .Values.aws.secretsName | quote }}
        property: google_api_key
    - secretKey: MISTRAL_API_KEY
      remoteRef:
        key: {{ .Values.aws.secretsName | quote }}
        property: mistral_api_key
    - secretKey: PRIVATE_MAIL_EMAIL_ID
      remoteRef:
        key: {{ .Values.aws.secretsName | quote }}
        property: private_mail_email_id
    - secretKey: PRIVATE_MAIL_PASSWORD
      remoteRef:
        key: {{ .Values.aws.secretsName | quote }}
        property: private_mail_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.poller.ssmSecretRef }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: {{ .Values.poller.ssmSecretRef }}
    creationPolicy: Owner
  data:
    - secretKey: HOST
      remoteRef:
        key: {{ printf "%s/private_mail_host" .Values.aws.ssmPathPrefix | quote }}
    - secretKey: IMAP_PORT
      remoteRef:
        key: {{ printf "%s/imap_port" .Values.aws.ssmPathPrefix | quote }}
    - secretKey: SMTP_PORT
      remoteRef:
        key: {{ printf "%s/smtp_port" .Values.aws.ssmPathPrefix | quote }}
    - secretKey: REDIS_STREAM_NAME
      remoteRef:
        key: {{ printf "%s/redis_stream_name" .Values.aws.ssmPathPrefix | quote }}
    - secretKey: REDIS_CONSUMER_GROUP
      remoteRef:
        key: {{ printf "%s/redis_consumer_group_name" .Values.aws.ssmPathPrefix | quote }}
{{- end }}
