{{- if .Values.aws.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region | quote }}
{{- end }}
