apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    kubernetes.io/description: "Install external-secrets controller to sync secrets from AWS Secrets Manager"
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: {{ index .Values "external-secrets" "version" }}
    helm:
      parameters:
        - name: installCRDs
          value: "false"
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: {{ index .Values "external-secrets" "serviceaccountname" }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ index .Values "external-secrets" "namespace" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true