clusterName: "complaint-responder-cluster"
environment: "dev"

karpenter:
  version: "1.13.0"
  serviceaccountname: karpenter

external-secrets:
  version: "2.7.0"
  namespace: "external-secrets"
  serviceaccountname: "external-secrets"
