apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-complaint-responder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: helm/Customer-Complaint-Responder
  destination:
    server: https://kubernetes.default.svc
    namespace: complaint-responder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
